// This file is part of Darwinia.
//
// Copyright (C) 2018-2022 Darwinia Network
// SPDX-License-Identifier: GPL-3.0
//
// Darwinia is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Darwinia is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Darwinia. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `from_substrate_issuing`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-07-13, STEPS: `2`, REPEAT: 2, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("pangolin-dev"), DB CACHE: 128

// Executed Command:
// ./target/release/drml
// benchmark
// --header
// .maintain/lincense-header
// --execution
// wasm
// --heap-pages
// 4096
// --steps
// 2
// --repeat
// 2
// --chain
// pangolin-dev
// --output
// node/runtime/pangolin/src/weights/
// --extrinsic
// *
// --pallet
// *


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `from_substrate_issuing`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> from_substrate_issuing::WeightInfo for WeightInfo<T> {
	// Storage: Substrate2SubstrateIssuing RemoteBackingAccount (r:1 w:0)
	// Storage: Substrate2SubstrateIssuing MappingFactoryAddress (r:1 w:0)
	// Storage: System Account (r:4 w:3)
	// Storage: Ethereum RemainingRingBalance (r:4 w:0)
	// Storage: EVM AccountCodes (r:3 w:1)
	// Storage: EVM AccountStorages (r:17 w:15)
	// Storage: Ethereum Pending (r:1 w:1)
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	fn register_from_remote() -> Weight {
		(1_064_465_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(35 as Weight))
			.saturating_add(T::DbWeight::get().writes(22 as Weight))
	}
	// Storage: Substrate2SubstrateIssuing RemoteBackingAccount (r:1 w:0)
	// Storage: Substrate2SubstrateIssuing MappingFactoryAddress (r:1 w:0)
	// Storage: System Account (r:4 w:1)
	// Storage: Ethereum RemainingRingBalance (r:4 w:0)
	// Storage: EVM AccountCodes (r:4 w:0)
	// Storage: EVM AccountStorages (r:13 w:3)
	// Storage: Ethereum Pending (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: BridgePangoroMessages InboundLanes (r:1 w:0)
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	fn issue_from_remote() -> Weight {
		(527_238_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(34 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
	// Storage: Substrate2SubstrateIssuing MappingFactoryAddress (r:1 w:1)
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	fn set_mapping_factory_address() -> Weight {
		(21_737_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: Substrate2SubstrateIssuing RemoteBackingAccount (r:0 w:1)
	fn set_remote_backing_account() -> Weight {
		(12_617_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
}
