// This file is part of Darwinia.
//
// Copyright (C) 2018-2022 Darwinia Network
// SPDX-License-Identifier: GPL-3.0
//
// Darwinia is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Darwinia is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Darwinia. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_fee_market`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-01, STEPS: `3`, REPEAT: 3, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("pangolin-dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/drml
// benchmark
// --header
// .maintain/lincense-header
// --chain
// pangolin-dev
// --execution
// wasm
// --heap-pages
// 4096
// --steps
// 3
// --repeat
// 3
// --output
// node/runtime/pangolin/src/weights/
// --extrinsic
// *
// --pallet
// pallet_fee_market

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_fee_market`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_fee_market::WeightInfo for WeightInfo<T> {
	// Storage: PangolinParachainFeeMarket Relayers (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PangolinParachainFeeMarket RelayersMap (r:10 w:1)
	// Storage: PangolinParachainFeeMarket Orders (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayers (r:0 w:1)
	fn enroll_and_lock_collateral() -> Weight {
		(114_385_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: PangolinParachainFeeMarket Relayers (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: PangolinParachainFeeMarket RelayersMap (r:10 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PangolinParachainFeeMarket Orders (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayers (r:0 w:1)
	fn increase_locked_collateral() -> Weight {
		(111_599_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: PangolinParachainFeeMarket Relayers (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: PangolinParachainFeeMarket RelayersMap (r:10 w:1)
	// Storage: PangolinParachainFeeMarket Orders (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PangolinParachainFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayers (r:0 w:1)
	fn decrease_locked_collateral() -> Weight {
		(118_442_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: PangolinParachainFeeMarket Relayers (r:1 w:0)
	// Storage: PangolinParachainFeeMarket RelayersMap (r:10 w:1)
	// Storage: PangolinParachainFeeMarket Orders (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayers (r:0 w:1)
	fn update_relay_fee() -> Weight {
		(98_014_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(13 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: PangolinParachainFeeMarket Relayers (r:1 w:1)
	// Storage: PangolinParachainFeeMarket Orders (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: PangolinParachainFeeMarket AssignedRelayers (r:1 w:1)
	// Storage: PangolinParachainFeeMarket RelayersMap (r:9 w:1)
	// Storage: PangolinParachainFeeMarket AssignedRelayersNumber (r:1 w:0)
	fn cancel_enrollment() -> Weight {
		(110_918_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: PangolinParachainFeeMarket CollateralSlashProtect (r:0 w:1)
	fn set_slash_protect() -> Weight {
		(9_658_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PangolinParachainFeeMarket Relayers (r:1 w:0)
	// Storage: PangolinParachainFeeMarket RelayersMap (r:10 w:0)
	// Storage: PangolinParachainFeeMarket Orders (r:1 w:0)
	// Storage: PangolinParachainFeeMarket AssignedRelayers (r:0 w:1)
	// Storage: PangolinParachainFeeMarket AssignedRelayersNumber (r:0 w:1)
	fn set_assigned_relayers_number() -> Weight {
		(93_295_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(12 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
