// This file is part of Darwinia.
//
// Copyright (C) 2018-2022 Darwinia Network
// SPDX-License-Identifier: GPL-3.0
//
// Darwinia is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Darwinia is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Darwinia. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_fee_market`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-01, STEPS: `3`, REPEAT: 3, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("pangolin-dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/drml
// benchmark
// --header
// .maintain/lincense-header
// --chain
// pangolin-dev
// --execution
// wasm
// --heap-pages
// 4096
// --steps
// 3
// --repeat
// 3
// --output
// node/runtime/pangolin/src/weights/
// --extrinsic
// *
// --pallet
// pallet_fee_market

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_fee_market`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_fee_market::WeightInfo for WeightInfo<T> {
	// Storage: PangoroFeeMarket Relayers (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PangoroFeeMarket RelayersMap (r:10 w:1)
	// Storage: PangoroFeeMarket Orders (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayers (r:0 w:1)
	fn enroll_and_lock_collateral() -> Weight {
		(115_366_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: PangoroFeeMarket Relayers (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: PangoroFeeMarket RelayersMap (r:10 w:1)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PangoroFeeMarket Orders (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayers (r:0 w:1)
	fn increase_locked_collateral() -> Weight {
		(113_513_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: PangoroFeeMarket Relayers (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: PangoroFeeMarket RelayersMap (r:10 w:1)
	// Storage: PangoroFeeMarket Orders (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: PangoroFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayers (r:0 w:1)
	fn decrease_locked_collateral() -> Weight {
		(122_991_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: PangoroFeeMarket Relayers (r:1 w:0)
	// Storage: PangoroFeeMarket RelayersMap (r:10 w:1)
	// Storage: PangoroFeeMarket Orders (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayersNumber (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayers (r:0 w:1)
	fn update_relay_fee() -> Weight {
		(100_969_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(13 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: PangoroFeeMarket Relayers (r:1 w:1)
	// Storage: PangoroFeeMarket Orders (r:1 w:0)
	// Storage: Balances Locks (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: PangoroFeeMarket AssignedRelayers (r:1 w:1)
	// Storage: PangoroFeeMarket RelayersMap (r:9 w:1)
	// Storage: PangoroFeeMarket AssignedRelayersNumber (r:1 w:0)
	fn cancel_enrollment() -> Weight {
		(112_390_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(15 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: PangoroFeeMarket CollateralSlashProtect (r:0 w:1)
	fn set_slash_protect() -> Weight {
		(10_139_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PangoroFeeMarket Relayers (r:1 w:0)
	// Storage: PangoroFeeMarket RelayersMap (r:10 w:0)
	// Storage: PangoroFeeMarket Orders (r:1 w:0)
	// Storage: PangoroFeeMarket AssignedRelayers (r:0 w:1)
	// Storage: PangoroFeeMarket AssignedRelayersNumber (r:0 w:1)
	fn set_assigned_relayers_number() -> Weight {
		(91_712_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(12 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
