// This file is part of Substrate.

// Copyright (C) 2020 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for from_ethereum_issuing
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-08-04, STEPS: [100, ], REPEAT: 10, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/drml
// benchmark
// --chain
// dev
// --wasm-execution
// compiled
// --pallet
// from_ethereum_issuing
// --execution
// wasm
// --extrinsic=*
// --steps
// 100
// --repeat
// 10
// --raw
// --heap-pages=4096
// --output=./frame/bridge/ethereum/issuing/src/weight.rs
// --template=./.maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for from_ethereum_issuing.
pub trait WeightInfo {
	fn register_erc20() -> Weight;
	fn redeem_erc20() -> Weight;
	fn register_response_from_contract() -> Weight;
	fn deposit_burn_token_event_from_precompile() -> Weight;
	fn set_mapping_factory_address() -> Weight;
	fn set_ethereum_backing_address() -> Weight;
}

/// Weights for from_ethereum_issuing using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_erc20() -> Weight {
		(1_088_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(14 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}

	fn redeem_erc20() -> Weight {
		(1_084_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(14 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}

	fn register_response_from_contract() -> Weight {
		(30_000_000 as Weight).saturating_add(T::DbWeight::get().reads(1 as Weight))
	}

	fn deposit_burn_token_event_from_precompile() -> Weight {
		(30_000_000 as Weight).saturating_add(T::DbWeight::get().reads(1 as Weight))
	}

	fn set_mapping_factory_address() -> Weight {
		(92_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}

	fn set_ethereum_backing_address() -> Weight {
		(99_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn register_erc20() -> Weight {
		(1_088_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(14 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}

	fn redeem_erc20() -> Weight {
		(1_084_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(14 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}

	fn register_response_from_contract() -> Weight {
		(30_000_000 as Weight).saturating_add(RocksDbWeight::get().reads(1 as Weight))
	}

	fn deposit_burn_token_event_from_precompile() -> Weight {
		(30_000_000 as Weight).saturating_add(RocksDbWeight::get().reads(1 as Weight))
	}

	fn set_mapping_factory_address() -> Weight {
		(92_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}

	fn set_ethereum_backing_address() -> Weight {
		(99_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
}
